import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import Main from '../components/Main'
import Projects from '../components/Projects'
import About from '../components/About'
import Skills from '../components/Skills'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Griffin | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Main />
      <About />
      <Projects />
      <Skills />
      

    </div>
  )
}
